import React,{Suspense,useEffect,useRef}from"react";import{createRoot}from"react-dom/client";import{Canvas,useFrame}from"@react-three/fiber";import{Float,Points,PointMaterial}from"@react-three/drei";import*as THREE from"three";import gsap from"gsap";import{ScrollTrigger}from"gsap/ScrollTrigger";import{ArrowUpRight,Code2,Database,BrainCircuit,Network}from"lucide-react";import"./style.css";gsap.registerPlugin(ScrollTrigger);

const projects=[
["01","Machine Learning","A reproducible scikit-learn pipeline for preprocessing, training, evaluation, serialization and inference.","PYTHON / SCIKIT-LEARN"],
["02","Deep Learning","TensorFlow/Keras and PyTorch implementations covering neural-network training and held-out evaluation.","TENSORFLOW / PYTORCH"],
["03","Transformer NLP","Pretrained transformer inference with clear separation between reused models and original engineering.","HUGGING FACE / NLP"],
["04","LLM Fine-Tuning","A configurable educational workflow for causal language-model adaptation using user-supplied datasets.","TRANSFORMERS / DATASETS"],
["05","RAG Retrieval","Inspectable semantic retrieval with sentence embeddings, chunking and FAISS similarity search.","FAISS / EMBEDDINGS"],
["06","Agentic AI","Controlled, auditable agent tool routing built around explicit allow-listed execution boundaries.","AGENTS / TOOL USE"]];

function Core(){const g=useRef(),ring=useRef();useFrame((s,d)=>{if(g.current){g.current.rotation.y+=d*.08;g.current.rotation.x=Math.sin(s.clock.elapsedTime*.18)*.18}if(ring.current)ring.current.rotation.z-=d*.12});return <group ref={g}><Float speed={1.4}rotationIntensity={.35}floatIntensity={.7}><mesh><icosahedronGeometry args={[1.35,5]}/><meshPhysicalMaterial color="#7857ff" roughness={.18}metalness={.25}transmission={.15}wireframe/></mesh><mesh scale={.72}><icosahedronGeometry args={[1.35,3]}/><meshPhysicalMaterial color="#d9d1ff" emissive="#6d4cff" emissiveIntensity={1.4}roughness={.25}/></mesh></Float><mesh ref={ring} rotation={[1.1,.2,.4]}><torusGeometry args={[2.15,.012,8,160]}/><meshBasicMaterial color="#8b75ff" transparent opacity={.65}/></mesh></group>}
function Stars(){const p=React.useMemo(()=>{const a=new Float32Array(1500*3);for(let i=0;i<a.length;i++)a[i]=(Math.random()-.5)*18;return a},[]);return <Points positions={p} stride={3}><PointMaterial transparent color="#8975ff" size={.012} sizeAttenuation depthWrite={false} opacity={.55}/></Points>}
function Scene(){return <div className="scene"><Canvas camera={{position:[0,0,6],fov:42}} dpr={[1,1.7]}><ambientLight intensity={.3}/><pointLight position={[3,3,4]} intensity={8} color="#7b5cff"/><Suspense fallback={null}><Stars/><Core/></Suspense></Canvas></div>}
function App(){useEffect(()=>{const ctx=gsap.context(()=>{gsap.utils.toArray(".reveal").forEach(el=>gsap.fromTo(el,{y:70,opacity:0},{y:0,opacity:1,duration:1,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 88%"}}));gsap.to(".scene",{yPercent:38,scale:.78,opacity:.3,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:true}});});return()=>ctx.revert()},[]);return <><Scene/><header><a className="brand" href="#">M/MG<span>.</span></a><nav><a href="#work">Work</a><a href="#about">About</a><a href="#credential">Credential</a></nav><a className="available" href="https://github.com/Kakarothz/MyWebPortfolio" target="_blank">GitHub <ArrowUpRight size={14}/></a></header><main>
<section className="hero"><div className="kicker">AI ENGINEERING / 2026</div><h1><span>BUILDING</span><span className="outline">INTELLIGENCE</span><span>INTO SYSTEMS.</span></h1><div className="heroFoot"><p>Machine learning, deep learning, LLMs, retrieval and agent systems — engineered as practical, inspectable software.</p><div className="scroll">SCROLL TO EXPLORE <i/></div></div></section>
<section className="statement reveal" id="about"><div className="sectionNo">01 / PROFILE</div><p>I turn <em>AI concepts</em> into working systems — from classical models and neural networks to transformer pipelines, retrieval architectures and controlled AI agents.</p></section>
<section id="work" className="work"><div className="titleRow reveal"><div><div className="sectionNo">02 / SELECTED WORK</div><h2>ENGINEERING<br/><span>EXPERIMENTS</span></h2></div><p>Independent implementations demonstrating the technical areas covered across my AI engineering path.</p></div><div className="projects">{projects.map((x,i)=><article className="project reveal" key={x[0]}><div className="num">{x[0]}</div><div className="projectTitle"><h3>{x[1]}</h3><small>{x[3]}</small></div><p>{x[2]}</p><ArrowUpRight className="arrow"/></article>)}</div></section>
<section className="systems reveal"><div className="sectionNo">03 / CAPABILITIES</div><div className="capGrid"><div><BrainCircuit/><b>MODEL<br/>ENGINEERING</b></div><div><Database/><b>RETRIEVAL<br/>SYSTEMS</b></div><div><Network/><b>AGENT<br/>WORKFLOWS</b></div><div><Code2/><b>AI<br/>AUTOMATION</b></div></div></section>
<section id="credential" className="credential"><div className="glow"/><div className="credentialInner reveal"><div className="sectionNo">04 / CREDENTIAL</div><h2>IBM AI<br/><span>ENGINEERING</span></h2><div className="credentialMeta"><p>Professional Certificate<br/>13-course program<br/>Completed September 2026</p><a href="https://coursera.org/verify/professional-cert/L3M5IUXRK04G" target="_blank">VERIFY CREDENTIAL <ArrowUpRight/></a></div></div></section>
</main><footer><div><b>MOHAMMAD<br/>MUSTAQIM GHAZALI</b><p>AI Engineering Portfolio</p></div><a href="https://github.com/Kakarothz" target="_blank">GITHUB ↗</a><div className="copy">© 2026 / KUALA LUMPUR</div></footer></>}
createRoot(document.getElementById("root")).render(<App/>);