import React,{useEffect,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{motion,useScroll,useTransform,MotionValue}from"framer-motion";
import{ArrowUpRight}from"lucide-react";
import"./index.css";

const gifs=[
"https://motionsites.ai/assets/hero-space-voyage-preview-eECLH3Yc.gif","https://motionsites.ai/assets/hero-codenest-preview-Cgppc2qV.gif","https://motionsites.ai/assets/hero-vex-ventures-preview-BczMFIiw.gif","https://motionsites.ai/assets/hero-stellar-ai-v2-preview-DjvxjG3C.gif","https://motionsites.ai/assets/hero-asme-preview-B_nGDnTP.gif","https://motionsites.ai/assets/hero-transform-data-preview-Cx5OU29N.gif","https://motionsites.ai/assets/hero-vitara-preview-Cjz2QYyU.gif","https://motionsites.ai/assets/hero-terra-preview-BFjrCr7T.gif","https://motionsites.ai/assets/hero-skyelite-preview-DHaZIgUv.gif","https://motionsites.ai/assets/hero-aethera-preview-DknSlcTa.gif","https://motionsites.ai/assets/hero-designpro-preview-D8c5_een.gif","https://motionsites.ai/assets/hero-stellar-ai-preview-D3HL6bw1.gif","https://motionsites.ai/assets/hero-xportfolio-preview-D4A8maiC.gif","https://motionsites.ai/assets/hero-orbit-web3-preview-BXt4OttD.gif","https://motionsites.ai/assets/hero-nexora-preview-cx5HmUgo.gif","https://motionsites.ai/assets/hero-evr-ventures-preview-DZxeVFEX.gif","https://motionsites.ai/assets/hero-planet-orbit-preview-DWAP8Z1P.gif","https://motionsites.ai/assets/hero-new-era-preview-CocuDUm9.gif","https://motionsites.ai/assets/hero-wealth-preview-B70idl_u.gif","https://motionsites.ai/assets/hero-luminex-preview-CxOP7ce6.gif","https://motionsites.ai/assets/hero-celestia-preview-0yO3jXO8.gif"];
const projects=[
{n:"01",category:"Machine Learning",name:"ML Pipeline",imgs:["https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055344_5eff02e0-87a5-41ce-b64f-eb08da8f33db.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055431_11d841fd-8b41-46a5-82e4-b04f2407a7d8.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055451_e317bf2d-28d4-48cc-86b0-6f72f25b6327.png&w=1280&q=85"]},
{n:"02",category:"Generative AI",name:"RAG Retrieval",imgs:["https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055654_911201c5-36d9-4bc6-bac7-331adfce159f.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055723_5ceda0b8-d9c2-4665-b2e3-83ba19ba76d1.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055753_adc5dcbd-a8e6-49c0-b43a-9b030d835cea.png&w=1280&q=85"]},
{n:"03",category:"Agentic AI",name:"Agent Workflow",imgs:["https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055759_963cfb0b-4bd1-4b0f-9d0a-09bd6cf95b2f.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_060108_438f781a-9846-4dcc-89ab-c4e6cb830f5b.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055818_9d062121-ad7e-46b9-999a-1a6a692ef1ee.png&w=1280&q=85"]}];
const services=[
["01","Machine Learning","Reproducible Python and scikit-learn workflows covering preprocessing, supervised learning, evaluation, serialization and inference."],
["02","Deep Learning","Neural-network implementations with TensorFlow, Keras and PyTorch, including training and held-out evaluation workflows."],
["03","LLM Engineering","Transformer and language-model workflows spanning pretrained inference, data preparation and educational fine-tuning pipelines."],
["04","RAG Systems","Semantic retrieval architectures using embeddings, chunking and FAISS similarity search with inspectable retrieval results."],
["05","AI Agents & Automation","Controlled AI workflows with explicit tool routing, allow-listed execution boundaries and practical automation patterns."]];

function FadeIn({children,delay=0,duration=.7,x=0,y=30,className=""}:{children:React.ReactNode,delay?:number,duration?:number,x?:number,y?:number,className?:string}){return <motion.div className={className} initial={{opacity:0,x,y}} whileInView={{opacity:1,x:0,y:0}} viewport={{once:true,margin:"50px",amount:0}} transition={{delay,duration,ease:[.25,.1,.25,1]}}>{children}</motion.div>}
function ContactButton(){return <a href="#contact" className="inline-flex rounded-full px-8 py-3 sm:px-10 sm:py-3.5 md:px-12 md:py-4 text-xs sm:text-sm md:text-base font-medium uppercase tracking-widest text-white outline outline-2 outline-white outline-offset-[-3px] transition-transform hover:scale-[1.03]" style={{background:"linear-gradient(123deg,#18011F 7%,#B600A8 37%,#7621B0 72%,#BE4C00 100%)",boxShadow:"0 4px 4px rgba(181,1,167,.25),4px 4px 12px #7721B1 inset"}}>Contact Me</a>}
function LiveProjectButton(){return <a href="https://github.com/Kakarothz/MyWebPortfolio" target="_blank" rel="noreferrer" className="rounded-full border-2 border-[#D7E2EA] px-8 py-3 sm:px-10 sm:py-3.5 text-sm sm:text-base font-medium uppercase tracking-widest text-[#D7E2EA] hover:bg-[#D7E2EA]/10">View Project</a>}
function Magnet({children,padding=150,strength=3}:{children:React.ReactNode,padding?:number,strength?:number}){const ref=useRef<HTMLDivElement>(null);const[xy,setXY]=useState([0,0]);const active=useRef(false);useEffect(()=>{const move=(e:MouseEvent)=>{const el=ref.current;if(!el)return;const r=el.getBoundingClientRect();const cx=r.left+r.width/2,cy=r.top+r.height/2;const inside=e.clientX>r.left-padding&&e.clientX<r.right+padding&&e.clientY>r.top-padding&&e.clientY<r.bottom+padding;active.current=inside;setXY(inside?[(e.clientX-cx)/strength,(e.clientY-cy)/strength]:[0,0])};window.addEventListener("mousemove",move,{passive:true});return()=>window.removeEventListener("mousemove",move)},[padding,strength]);return <div ref={ref} style={{transform:`translate3d(${xy[0]}px,${xy[1]}px,0)`,transition:active.current?"transform .3s ease-out":"transform .6s ease-in-out",willChange:"transform"}}>{children}</div>}
function HeroSection(){return <section className="relative flex h-screen flex-col overflow-x-clip bg-[#0C0C0C]"><FadeIn y={-20}><nav className="relative z-30 flex justify-between px-6 pt-6 md:px-10 md:pt-8">{["About","Price","Projects","Contact"].map(x=><a key={x} href={x==="About"?"#about":x==="Projects"?"#projects":"#contact"} className="text-sm md:text-lg lg:text-[1.4rem] font-medium uppercase tracking-wider text-[#D7E2EA] transition-opacity duration-200 hover:opacity-70">{x}</a>)}</nav></FadeIn><div className="overflow-hidden"><FadeIn delay={.15} y={40}><h1 className="hero-heading mt-6 sm:mt-4 md:-mt-5 w-full whitespace-nowrap text-[14vw] sm:text-[15vw] md:text-[16vw] lg:text-[17.5vw] font-black uppercase leading-none tracking-tight">Hi, i&apos;m mustaqim</h1></FadeIn></div><FadeIn delay={.6} y={30} className="pointer-events-none absolute left-1/2 top-1/2 z-10 w-[280px] -translate-x-1/2 -translate-y-1/2 sm:top-auto sm:bottom-0 sm:w-[360px] sm:translate-y-0 md:w-[440px] lg:w-[520px]"><Magnet><img className="pointer-events-auto w-full" src="https://shrug-person-78902957.figma.site/_components/v2/d24c01ad3a56fc65e942a1f501eb73db42d7cf9a/Rectangle_40443.81459862.png" alt="Mohammad Mustaqim Ghazali"/></Magnet></FadeIn><div className="relative z-20 mt-auto flex items-end justify-between px-6 pb-7 sm:pb-8 md:px-10 md:pb-10"><FadeIn delay={.35} y={20}><p className="max-w-[160px] sm:max-w-[220px] md:max-w-[260px] text-[#D7E2EA] font-light uppercase tracking-wide leading-snug" style={{fontSize:"clamp(.75rem,1.4vw,1.5rem)"}}>an ai engineer building practical, inspectable systems across machine learning, llms, retrieval and automation</p></FadeIn><FadeIn delay={.5} y={20}><ContactButton/></FadeIn></div></section>}
function MarqueeSection(){const ref=useRef<HTMLElement>(null);const[offset,setOffset]=useState(0);useEffect(()=>{const onScroll=()=>{if(!ref.current)return;setOffset((window.scrollY+window.innerHeight-ref.current.offsetTop)*.3)};onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);const row=(items:string[],dir:number)=><div className="flex w-max gap-3" style={{transform:`translate3d(${dir*(offset-200)}px,0,0)`,willChange:"transform"}}>{[...items,...items,...items].map((src,i)=><img key={i} src={src} loading="lazy" alt="" className="h-[270px] w-[420px] shrink-0 rounded-2xl object-cover"/>)}</div>;return <section ref={ref} className="overflow-hidden bg-[#0C0C0C] pt-24 sm:pt-32 md:pt-40 pb-10"><div className="flex flex-col gap-3">{row(gifs.slice(0,11),1)}{row(gifs.slice(11),-1)}</div></section>}
function AnimatedText(){const text="I build practical AI and automation systems across machine learning, deep learning, language models, retrieval and controlled agent workflows. My portfolio focuses on turning AI concepts into working, inspectable software with clear engineering boundaries.";const ref=useRef<HTMLParagraphElement>(null);const{scrollYProgress}=useScroll({target:ref,offset:["start 0.8","end 0.2"]});return <p ref={ref} className="relative max-w-[560px] text-center text-[#D7E2EA] font-medium leading-relaxed" style={{fontSize:"clamp(1rem,2vw,1.35rem)"}}>{text.split("").map((c,i)=><Char key={i} c={c} i={i} total={text.length} p={scrollYProgress}/>)}</p>}
function Char({c,i,total,p}:{c:string,i:number,total:number,p:MotionValue<number>}){const opacity=useTransform(p,[i/total,Math.min(1,i/total+.08)],[.2,1]);return <span className="relative inline-block"><span className="invisible">{c===" "?"\u00A0":c}</span><motion.span style={{opacity}} className="absolute inset-0">{c===" "?"\u00A0":c}</motion.span></span>}
function AboutSection(){return <section id="about" className="relative flex min-h-screen items-center justify-center overflow-hidden px-5 py-20 sm:px-8 md:px-10"><FadeIn delay={.1} x={-80} y={0} duration={.9} className="absolute left-[1%] sm:left-[2%] md:left-[4%] top-[4%] w-[120px] sm:w-[160px] md:w-[210px]"><img src="https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/moon_icon.11395d36.png" alt=""/></FadeIn><FadeIn delay={.25} x={-80} y={0} duration={.9} className="absolute bottom-[8%] left-[3%] sm:left-[6%] md:left-[10%] w-[100px] sm:w-[140px] md:w-[180px]"><img src="https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/p59_1.4659672e.png" alt=""/></FadeIn><FadeIn delay={.15} x={80} y={0} duration={.9} className="absolute right-[1%] sm:right-[2%] md:right-[4%] top-[4%] w-[120px] sm:w-[160px] md:w-[210px]"><img src="https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/lego_icon-1.703bb594.png" alt=""/></FadeIn><FadeIn delay={.3} x={80} y={0} duration={.9} className="absolute bottom-[8%] right-[3%] sm:right-[6%] md:right-[10%] w-[130px] sm:w-[170px] md:w-[220px]"><img src="https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/Group_134-1.2e04f3ce.png" alt=""/></FadeIn><div className="relative z-10 flex flex-col items-center gap-10 sm:gap-14 md:gap-16"><FadeIn y={40}><h2 className="hero-heading text-center font-black uppercase leading-none tracking-tight" style={{fontSize:"clamp(3rem,12vw,160px)"}}>About me</h2></FadeIn><div className="flex flex-col items-center gap-16 sm:gap-20 md:gap-24"><AnimatedText/><ContactButton/></div></div></section>}
function ServicesSection(){return <section className="rounded-t-[40px] sm:rounded-t-[50px] md:rounded-t-[60px] bg-white px-5 py-20 sm:px-8 sm:py-24 md:px-10 md:py-32 text-[#0C0C0C]"><h2 className="mb-16 sm:mb-20 md:mb-28 text-center font-black uppercase leading-none" style={{fontSize:"clamp(3rem,12vw,160px)"}}>Services</h2><div className="mx-auto max-w-5xl border-t border-black/15">{services.map((s,i)=><FadeIn key={s[0]} delay={i*.1}><div className="grid grid-cols-[.55fr_1fr] items-start border-b border-black/15 py-8 sm:py-10 md:py-12"><div className="font-black leading-none" style={{fontSize:"clamp(3rem,10vw,140px)"}}>{s[0]}</div><div className="pt-2 md:pt-5"><h3 className="font-medium uppercase" style={{fontSize:"clamp(1rem,2.2vw,2.1rem)"}}>{s[1]}</h3><p className="mt-3 max-w-2xl font-light leading-relaxed opacity-60" style={{fontSize:"clamp(.85rem,1.6vw,1.25rem)"}}>{s[2]}</p></div></div></FadeIn>)}</div></section>}
function ProjectCard({p,index,total}:{p:(typeof projects)[number],index:number,total:number}){const ref=useRef<HTMLDivElement>(null);const{scrollYProgress}=useScroll({target:ref,offset:["start end","end start"]});const scale=useTransform(scrollYProgress,[0,.65,1],[1,1,1-(total-1-index)*.03]);return <div ref={ref} className="relative h-[85vh]"><motion.article style={{scale,top:`calc(6rem + ${index*28}px)`}} className="sticky overflow-hidden rounded-[40px] sm:rounded-[50px] md:rounded-[60px] border-2 border-[#D7E2EA] bg-[#0C0C0C] p-4 sm:p-6 md:p-8"><div className="mb-5 grid grid-cols-[auto_1fr_auto] items-center gap-5 text-[#D7E2EA]"><div className="font-black leading-none" style={{fontSize:"clamp(3rem,8vw,110px)"}}>{p.n}</div><div><div className="text-xs uppercase tracking-widest opacity-60">{p.category}</div><h3 className="text-xl sm:text-3xl md:text-5xl font-medium uppercase">{p.name}</h3></div><LiveProjectButton/></div><div className="grid grid-cols-[40%_60%] gap-3"><div className="flex flex-col gap-3"><img src={p.imgs[0]} className="w-full rounded-[40px] sm:rounded-[50px] md:rounded-[60px] object-cover" style={{height:"clamp(130px,16vw,230px)"}}/><img src={p.imgs[1]} className="w-full rounded-[40px] sm:rounded-[50px] md:rounded-[60px] object-cover" style={{height:"clamp(160px,22vw,340px)"}}/></div><img src={p.imgs[2]} className="h-full min-h-[303px] w-full rounded-[40px] sm:rounded-[50px] md:rounded-[60px] object-cover"/></div></motion.article></div>}
function ProjectsSection(){return <section id="projects" className="relative z-10 -mt-10 sm:-mt-12 md:-mt-14 rounded-t-[40px] sm:rounded-t-[50px] md:rounded-t-[60px] bg-[#0C0C0C] px-5 py-20 sm:px-8 md:px-10"><h2 className="hero-heading mb-20 text-center font-black uppercase leading-none tracking-tight" style={{fontSize:"clamp(3rem,12vw,160px)"}}>Projects</h2><div className="mx-auto max-w-7xl">{projects.map((p,i)=><ProjectCard key={p.n} p={p} index={i} total={projects.length}/>)}</div><div id="contact" className="flex min-h-[55vh] flex-col items-center justify-center gap-8 text-center"><h2 className="hero-heading font-black uppercase leading-none" style={{fontSize:"clamp(3rem,10vw,140px)"}}>Building intelligence.</h2><ContactButton/></div></section>}
function App(){return <main className="overflow-x-clip bg-[#0C0C0C]"><HeroSection/><MarqueeSection/><AboutSection/><ServicesSection/><ProjectsSection/></main>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);