import React,{useEffect,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{motion,useScroll,useTransform,MotionValue}from"framer-motion";
import"./index.css";

const gifs=[
"https://motionsites.ai/assets/hero-space-voyage-preview-eECLH3Yc.gif","https://motionsites.ai/assets/hero-codenest-preview-Cgppc2qV.gif","https://motionsites.ai/assets/hero-vex-ventures-preview-BczMFIiw.gif","https://motionsites.ai/assets/hero-stellar-ai-v2-preview-DjvxjG3C.gif","https://motionsites.ai/assets/hero-asme-preview-B_nGDnTP.gif","https://motionsites.ai/assets/hero-transform-data-preview-Cx5OU29N.gif","https://motionsites.ai/assets/hero-vitara-preview-Cjz2QYyU.gif","https://motionsites.ai/assets/hero-terra-preview-BFjrCr7T.gif","https://motionsites.ai/assets/hero-skyelite-preview-DHaZIgUv.gif","https://motionsites.ai/assets/hero-aethera-preview-DknSlcTa.gif","https://motionsites.ai/assets/hero-designpro-preview-D8c5_een.gif","https://motionsites.ai/assets/hero-stellar-ai-preview-D3HL6bw1.gif","https://motionsites.ai/assets/hero-xportfolio-preview-D4A8maiC.gif","https://motionsites.ai/assets/hero-orbit-web3-preview-BXt4OttD.gif","https://motionsites.ai/assets/hero-nexora-preview-cx5HmUgo.gif","https://motionsites.ai/assets/hero-evr-ventures-preview-DZxeVFEX.gif","https://motionsites.ai/assets/hero-planet-orbit-preview-DWAP8Z1P.gif","https://motionsites.ai/assets/hero-new-era-preview-CocuDUm9.gif","https://motionsites.ai/assets/hero-wealth-preview-B70idl_u.gif","https://motionsites.ai/assets/hero-luminex-preview-CxOP7ce6.gif","https://motionsites.ai/assets/hero-celestia-preview-0yO3jXO8.gif"];
const projects=[
{n:"01",category:"Machine Learning",name:"ML Pipeline",imgs:["https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055344_5eff02e0-87a5-41ce-b64f-eb08da8f33db.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055431_11d841fd-8b41-46a5-82e4-b04f2407a7d8.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055451_e317bf2d-28d4-48cc-86b0-6f72f25b6327.png&w=1280&q=85"]},
{n:"02",category:"Generative AI",name:"RAG Retrieval",imgs:["https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055654_911201c5-36d9-4bc6-bac7-331adfce159f.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055723_5ceda0b8-d9c2-4665-b2e3-83ba19ba76d1.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055753_adc5dcbd-a8e6-49c0-b43a-9b030d835cea.png&w=1280&q=85"]},
{n:"03",category:"Agentic AI",name:"Agent Workflow",imgs:["https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055759_963cfb0b-4bd1-4b0f-9d0a-09bd6cf95b2f.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_060108_438f781a-9846-4dcc-89ab-c4e6cb830f5b.png&w=1280&q=85","https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260412_055818_9d062121-ad7e-46b9-999a-1a6a692ef1ee.png&w=1280&q=85"]}];
const services=[
["01","Machine Learning","Reproducible Python and scikit-learn workflows covering preprocessing, supervised learning, evaluation, serialization and inference."],
["02","Deep Learning","Neural-network implementations with TensorFlow, Keras and PyTorch, including training and held-out evaluation workflows."],
["03","LLM Engineering","Transformer and language-model workflows spanning pretrained inference, data preparation and educational fine-tuning pipelines."],
["04","RAG Systems","Semantic retrieval architectures using embeddings, chunking and FAISS similarity search with inspectable retrieval results."],
["05","AI Agents & Automation","Controlled AI workflows with explicit tool routing, allow-listed execution boundaries and practical automation patterns."]];

function FadeIn({children,delay=0,duration=.7,x=0,y=30,className=""}:{children:React.ReactNode,delay?:number,duration?:number,x?:number,y?:number,className?:string}){return <motion.div className={className} initial={{opacity:0,x,y}} whileInView={{opacity:1,x:0,y:0}} viewport={{once:true,margin:"50px",amount:0}} transition={{delay,duration,ease:[.25,.1,.25,1]}}>{children}</motion.div>}
function ContactButton(){return <a href="#contact" className="inline-flex rounded-full px-8 py-3 sm:px-10 sm:py-3.5 md:px-12 md:py-4 text-xs sm:text-sm md:text-base font-medium uppercase tracking-widest text-white outline outline-2 outline-white outline-offset-[-3px] transition-transform hover:scale-[1.03]" style={{background:"linear-gradient(123deg,#18011F 7%,#B600A8 37%,#7621B0 72%,#BE4C00 100%)",boxShadow:"0 4px 4px rgba(181,1,167,.25),4px 4px 12px #7721B1 inset"}}>Contact Me</a>}
function LiveProjectButton(){return <a href="https://github.com/Kakarothz/MyWebPortfolio" target="_blank" rel="noreferrer" className="rounded-full border-2 border-[#D7E2EA] px-8 py-3 sm:px-10 sm:py-3.5 text-sm sm:text-base font-medium uppercase tracking-widest text-[#D7E2EA] hover:bg-[#D7E2EA]/10">View Project</a>}
function Magnet({children,padding=150,strength=3}:{children:React.ReactNode,padding?:number,strength?:number}){const ref=useRef<HTMLDivElement>(null);const[xy,setXY]=useState([0,0]);const active=useRef(false);useEffect(()=>{const move=(e:MouseEvent)=>{const el=ref.current;if(!el)return;const r=el.getBoundingClientRect();const cx=r.left+r.width/2,cy=r.top+r.height/2;const inside=e.clientX>r.left-padding&&e.clientX<r.right+padding&&e.clientY>r.top-padding&&e.clientY<r.bottom+padding;active.current=inside;setXY(inside?[(e.clientX-cx)/strength,(e.clientY-cy)/strength]:[0,0])};window.addEventListener("mousemove",move,{passive:true});return()=>window.removeEventListener("mousemove",move)},[padding,strength]);return <div ref={ref} style={{transform:`translate3d(${xy[0]}px,${xy[1]}px,0)`,transition:active.current?"transform .3s ease-out":"transform .6s ease-in-out",willChange:"transform"}}>{children}</div>}
function HeroSection(){return <section className="relative flex min-h-[82vh] flex-col overflow-hidden bg-[#0C0C0C]"><video className="absolute inset-0 h-full w-full object-cover opacity-55" autoPlay muted loop playsInline preload="metadata"><source src="./hero.webm" type="video/webm"/><source src="./hero.mp4" type="video/mp4"/></video><div className="absolute inset-0 bg-gradient-to-b from-black/45 via-black/30 to-[#0C0C0C]/80"/><FadeIn y={-20}><nav className="relative z-30 flex justify-between px-6 pt-6 md:px-10 md:pt-8">{[["Profile","#about"],["Skills","#skills"],["Projects","#projects"],["Credential","#credential"]].map(([label,href])=><a key={label} href={href} className="text-xs md:text-base font-medium uppercase tracking-wider text-[#D7E2EA] transition-opacity duration-200 hover:opacity-70">{label}</a>)}</nav></FadeIn><div className="px-5 md:px-10 pt-10 md:pt-12"><FadeIn delay={.12} y={30}><p className="mb-3 text-xs md:text-sm uppercase tracking-[.24em] text-[#D7E2EA]/55">Mohammad Mustaqim Ghazali · AI Engineering Portfolio</p><h1 className="hero-heading max-w-[1500px] font-black uppercase leading-[.82] tracking-[-.055em]" style={{fontSize:"clamp(4.2rem,11.2vw,11.5rem)"}}>Mustaqim</h1></FadeIn></div><div className="relative z-20 mt-auto grid gap-8 px-6 pb-10 md:grid-cols-[1.1fr_.9fr] md:px-10 md:pb-12"><FadeIn delay={.3} y={20}><div><p className="text-[#D7E2EA] text-xl md:text-3xl font-medium uppercase">IT & AI Executive</p><p className="mt-3 max-w-2xl text-sm md:text-base font-light leading-relaxed text-[#D7E2EA]/65">Building operational automation and AI systems while developing practical engineering capability across machine learning, deep learning, LLMs, retrieval and agent workflows.</p></div></FadeIn><FadeIn delay={.4} y={20} className="md:text-right"><p className="text-xs uppercase tracking-[.2em] text-[#D7E2EA]/45">Current focus</p><p className="mt-2 text-sm md:text-base text-[#D7E2EA]">AI Engineering · Automation · System Development</p><a href="https://github.com/Kakarothz" target="_blank" rel="noreferrer" className="mt-5 inline-block border-b border-[#D7E2EA]/50 pb-1 text-xs uppercase tracking-[.18em] text-[#D7E2EA]">GitHub Profile ↗</a></FadeIn></div></section>}
function MarqueeSection(){const ref=useRef<HTMLElement>(null);const[offset,setOffset]=useState(0);useEffect(()=>{const onScroll=()=>{if(!ref.current)return;setOffset((window.scrollY+window.innerHeight-ref.current.offsetTop)*.3)};onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);const row=(items:string[],dir:number)=><div className="flex w-max gap-3" style={{transform:`translate3d(${dir*(offset-200)}px,0,0)`,willChange:"transform"}}>{[...items,...items,...items].map((src,i)=><img key={i} src={src} loading="lazy" alt="" className="h-[220px] w-[340px] md:h-[250px] md:w-[390px] shrink-0 rounded-2xl object-cover"/>)}</div>;return <section className="overflow-hidden bg-[#0C0C0C] py-16 md:py-20" ref={ref}><div className="flex flex-col gap-3">{row(gifs.slice(0,11),1)}{row(gifs.slice(11),-1)}</div></section>}
function AnimatedText(){const text="I work across IT operations, software automation and applied AI. This portfolio documents practical implementations in machine learning, deep learning, language models, retrieval and controlled agent workflows, with an emphasis on systems that can be inspected, maintained and used in real operations.";const ref=useRef<HTMLParagraphElement>(null);const{scrollYProgress}=useScroll({target:ref,offset:["start 0.8","end 0.2"]});return <p ref={ref} className="relative max-w-[560px] text-center text-[#D7E2EA] font-medium leading-relaxed" style={{fontSize:"clamp(1rem,2vw,1.35rem)"}}>{text.split("").map((c,i)=><Char key={i} c={c} i={i} total={text.length} p={scrollYProgress}/>)}</p>}
function Char({c,i,total,p}:{c:string,i:number,total:number,p:MotionValue<number>}){const opacity=useTransform(p,[i/total,Math.min(1,i/total+.08)],[.2,1]);return <span className="relative inline-block"><span className="invisible">{c===" "?"\u00A0":c}</span><motion.span style={{opacity}} className="absolute inset-0">{c===" "?"\u00A0":c}</motion.span></span>}
function AboutSection(){return <section id="about" className="relative flex min-h-[72vh] items-center justify-center px-5 py-20 sm:px-8 md:px-10"><div className="mx-auto flex max-w-5xl flex-col items-center gap-10 md:gap-12"><FadeIn y={30}><h2 className="hero-heading text-center font-black uppercase leading-none tracking-tight" style={{fontSize:"clamp(3rem,8vw,110px)"}}>Profile</h2></FadeIn><AnimatedText/><div className="grid w-full grid-cols-2 gap-px overflow-hidden rounded-3xl bg-white/10 md:grid-cols-4"><div className="bg-[#0C0C0C] p-5"><small className="text-[#D7E2EA]/40 uppercase tracking-widest">Role</small><p className="mt-2 text-[#D7E2EA]">IT & AI Executive</p></div><div className="bg-[#0C0C0C] p-5"><small className="text-[#D7E2EA]/40 uppercase tracking-widest">Education</small><p className="mt-2 text-[#D7E2EA]">Diploma in Pharmacy</p></div><div className="bg-[#0C0C0C] p-5"><small className="text-[#D7E2EA]/40 uppercase tracking-widest">Credential</small><p className="mt-2 text-[#D7E2EA]">IBM AI Engineering</p></div><div className="bg-[#0C0C0C] p-5"><small className="text-[#D7E2EA]/40 uppercase tracking-widest">GitHub</small><p className="mt-2 text-[#D7E2EA]">Kakarothz</p></div></div></div></section>}
function ServicesSection(){return <section id="skills" className="rounded-t-[40px] sm:rounded-t-[50px] md:rounded-t-[60px] bg-white px-5 py-16 sm:px-8 sm:py-20 md:px-10 md:py-24 text-[#0C0C0C]"><h2 className="mb-12 sm:mb-16 md:mb-20 text-center font-black uppercase leading-none" style={{fontSize:"clamp(3rem,8vw,110px)"}}>Technical Skills</h2><div className="mx-auto max-w-5xl border-t border-black/15">{services.map((s,i)=><FadeIn key={s[0]} delay={i*.1}><div className="grid grid-cols-[.55fr_1fr] items-start border-b border-black/15 py-6 sm:py-8 md:py-9"><div className="font-black leading-none" style={{fontSize:"clamp(3rem,10vw,140px)"}}>{s[0]}</div><div className="pt-2 md:pt-5"><h3 className="font-medium uppercase" style={{fontSize:"clamp(1rem,2.2vw,2.1rem)"}}>{s[1]}</h3><p className="mt-3 max-w-2xl font-light leading-relaxed opacity-60" style={{fontSize:"clamp(.85rem,1.6vw,1.25rem)"}}>{s[2]}</p></div></div></FadeIn>)}</div></section>}
function ProjectCard({p,index,total}:{p:(typeof projects)[number],index:number,total:number}){const ref=useRef<HTMLDivElement>(null);const{scrollYProgress}=useScroll({target:ref,offset:["start end","end start"]});const scale=useTransform(scrollYProgress,[0,.65,1],[1,1,1-(total-1-index)*.03]);return <div ref={ref} className="relative h-[85vh]"><motion.article style={{scale,top:`calc(6rem + ${index*28}px)`}} className="sticky overflow-hidden rounded-[40px] sm:rounded-[50px] md:rounded-[60px] border-2 border-[#D7E2EA] bg-[#0C0C0C] p-4 sm:p-6 md:p-8"><div className="mb-5 grid grid-cols-[auto_1fr_auto] items-center gap-5 text-[#D7E2EA]"><div className="font-black leading-none" style={{fontSize:"clamp(3rem,8vw,110px)"}}>{p.n}</div><div><div className="text-xs uppercase tracking-widest opacity-60">{p.category}</div><h3 className="text-xl sm:text-3xl md:text-5xl font-medium uppercase">{p.name}</h3></div><LiveProjectButton/></div><div className="grid grid-cols-[40%_60%] gap-3"><div className="flex flex-col gap-3"><img src={p.imgs[0]} className="w-full rounded-[40px] sm:rounded-[50px] md:rounded-[60px] object-cover" style={{height:"clamp(130px,16vw,230px)"}}/><img src={p.imgs[1]} className="w-full rounded-[40px] sm:rounded-[50px] md:rounded-[60px] object-cover" style={{height:"clamp(160px,22vw,340px)"}}/></div><img src={p.imgs[2]} className="h-full min-h-[303px] w-full rounded-[40px] sm:rounded-[50px] md:rounded-[60px] object-cover"/></div></motion.article></div>}
function ProjectsSection(){return <section id="projects" className="relative z-10 -mt-10 sm:-mt-12 md:-mt-14 rounded-t-[40px] sm:rounded-t-[50px] md:rounded-t-[60px] bg-[#0C0C0C] px-5 py-20 sm:px-8 md:px-10"><h2 className="hero-heading mb-20 text-center font-black uppercase leading-none tracking-tight" style={{fontSize:"clamp(3rem,12vw,160px)"}}>Projects</h2><div className="mx-auto max-w-7xl">{projects.map((p,i)=><ProjectCard key={p.n} p={p} index={i} total={projects.length}/>)}</div><div id="credential" className="mx-auto mt-12 max-w-5xl border-t border-white/15 py-16 text-center"><p className="text-xs uppercase tracking-[.25em] text-[#D7E2EA]/45">Professional Credential</p><h2 className="hero-heading mt-4 font-black uppercase leading-none" style={{fontSize:"clamp(2.8rem,7vw,90px)"}}>IBM AI Engineering</h2><p className="mx-auto mt-5 max-w-xl text-sm text-[#D7E2EA]/60">Professional Certificate · 13-course program · Completed September 2026</p><a href="https://coursera.org/verify/professional-cert/L3M5IUXRK04G" target="_blank" rel="noreferrer" className="mt-7 inline-block border-b border-[#D7E2EA]/50 pb-1 text-xs uppercase tracking-[.18em] text-[#D7E2EA]">Verify credential ↗</a></div></section>}
function App(){return <main className="overflow-x-clip bg-[#0C0C0C]"><HeroSection/><MarqueeSection/><AboutSection/><ServicesSection/><ProjectsSection/></main>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);